<div id="checkboxArea">
          <input type="checkbox" name="city_check" value="서울">서울
          <input type="checkbox" name="city_check" value="수원">수원
          <input type="checkbox" name="city_check" value="신탄진">신탄진
          <input type="checkbox" name="city_check" value="청평">청평
          <input type="checkbox" name="city_check" value="가평">가평
          <input type="checkbox" name="city_check" value="남춘천">남춘천
          <input type="checkbox" name="city_check" value="충주">충주
          <input type="checkbox" name="city_check" value="제천">제천<br/>
          <input type="checkbox" name="city_check" value="단양">단양
          <input type="checkbox" name="city_check" value="영주">영주
          <input type="checkbox" name="city_check" value="안동">안동
          <input type="checkbox" name="city_check" value="태백">태백
          <input type="checkbox" name="city_check" value="신기">신기
          <input type="checkbox" name="city_check" value="동해">동해
          <input type="checkbox" name="city_check" value="정동진">정동진
          <input type="checkbox" name="city_check" value="대천">대천<br/>
          <input type="checkbox" name="city_check" value="논산">논산
          <input type="checkbox" name="city_check" value="군산">군산
          <input type="checkbox" name="city_check" value="익산">익산
          <input type="checkbox" name="city_check" value="전주">전주
          <input type="checkbox" name="city_check" value="정읍">정읍
          <input type="checkbox" name="city_check" value="남원">남원
          <input type="checkbox" name="city_check" value="곡성">곡성
          <input type="checkbox" name="city_check" value="광주">광주<br/>
          <input type="checkbox" name="city_check" value="화순">화순
          <input type="checkbox" name="city_check" value="목포">목포
          <input type="checkbox" name="city_check" value="보성">보성
          <input type="checkbox" name="city_check" value="순천">순천
          <input type="checkbox" name="city_check" value="여수">여수
          <input type="checkbox" name="city_check" value="마산">마산
          <input type="checkbox" name="city_check" value="밀양">밀양
          <input type="checkbox" name="city_check" value="경주">경주
          <input type="checkbox" name="city_check" value="포항">포항
          <input type="checkbox" name="city_check" value="부산">부산
        </div>